project_id = "bifqtxaigahdhejurzyb"

[functions.telegram-notification]
verify_jwt = false

[functions.process-message-queue]
verify_jwt = false

[functions.ultramsg-webhook]
verify_jwt = false

[functions.send-sms]
verify_jwt = false